### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by syedzaidi-kiwi** [cohere-ai/DiskVectorIndex#2]
Traceback (most recent call last):
  File "/Users/kiwitech/Documents/DN-Final/dvindexer.py", line 3, in <module>
    from DiskVectorIndex import DiskVectorIndex
  File "/Users/kiwitech/Documents/DN-Final/venv/lib/python3.12/site-packages/DiskVectorIndex/__init__.py", line 3, in <module>
    from .DiskVectorIndex import DiskVectorIndex
  File "/Users/kiwitech/Documents/DN-Final/venv/lib/python3.12/site-packages/DiskVectorIndex/DiskVectorIndex.py", line 6, in <module>
    from indexed_zstd import IndexedZstdFile
ImportError: dlopen(/Users/kiwitech/Documents/DN-Final/venv/lib/python3.12/site-packages/indexed_zstd.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_ZSTD_DCtx_reset'

**Comment by nreimers** [comment]
Appears to be some error with zstd. Can you run zstd from console / cli?
